version: '3'

services :
    nginx:
        container_name: nginx
        image: nginx:nginx
        build: ./requirements/nginx/
        ports:
            - "443:443"
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - wordpressData:/var/www/html/
        depends_on:
            - wordpress
        networks:
            - netfornet
    mariadb:
        image: mariadb:mariadb
        container_name: mariadb
        build: ./requirements/mariadb/
        restart: unless-stopped
        ports:
            - "3306:3306"
        env_file:
            - .env
        networks:
            - netfornet
        volumes:
            - mariadb:/var/lib/mysql
    wordpress:
        image: wordpress:wordpress
        container_name: wordpress
        build: ./requirements/wordpress/
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - mariadb
        volumes:
            - wordpressData:/var/www/html/
        networks:
            - netfornet

volumes:
  wordpressData:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpressData/
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb/

networks:
    netfornet:
        driver: bridge
